### PR TITLE
"No Results" when searching.

### PR DESCRIPTION
**Pull request by alieus**
I was getting "No Results" when searching. The problem seems to be solved if
I add "&gws_rd=cr" (redirect to country server) in the search URL.

### CODE REVIEW

**Comment by eavgerinos** [comment]
Can you provide me with an example of "No Results" search with the current implementation? 

Thanks in advance :)

**Comment by alieus** [comment]
The response of www.google.com/search heavily depends on the user agent declared in the request (and probably other parameters such as the country). So it is possible that other system configuration get different results if `Net::HTTP.get` uses a different user agents for them...

But, here is what I get:
```bash
sta@Sand:~$ echo $(lsb_release -sir)
Ubuntu 14.04
sta@Sand:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
sta@Sand:~$ sudo gem install popme
[sudo] password for sta: 
Fetching: popme-1.0.4.gem (100%)
Successfully installed popme-1.0.4
1 gem installed
Installing ri documentation for popme-1.0.4...
Installing RDoc documentation for popme-1.0.4...
sta@Sand:~$ pop search github
No results
```

Now, if we modify `search.rd` to print the response:
```ruby
def response
    resp = Net::HTTP.get(request_uri).utf8_encode.unescape_html
    puts resp
    resp
  rescue => e
    puts "#{e.class}: #{e.message.strip}"
    ""
  end
```

We can see that Google answers with a `302 Moved`
```bash
sta@Sand:~/git/popme$ ruby bin/pop search github
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.gr/search?q=github&gws_rd=cr&ei=CAC9VMKLNsvNygOz0YKgBQ">here</A>.
</BODY></HTML>
No results
```

The moved url includes redirection to country server: `&gws_rd=cr`

Now, if we add this redirection parameter to the initial url:
```ruby
  def request_uri
    URI("#{URL}#{query.uri_encode}&gws_rd=cr")
  end
```

We get the expected result:
```bash
sta@Sand:~/git/popme$ ruby bin/pop search github
[0]	GitHub · Build software better, together.
	https://github.com/

[1]	GitHub - Wikipedia, the free encyclopedia
	en.wikipedia.org/wiki/GitHub

[2]	A list of cool features of Git and GitHub | Hacker News
	Hacker News - Y Combinator

[3]	GitHub (@github) | Twitter
	https://twitter.com/github

[4]	GitHub - Android Apps on Google Play
	https://play.google.com/store/apps/details?id=com.github...hl...

[5]	GitHub For Beginners: Don't Get Scared, Get Started - ReadWrite
	readwrite.com/.../understanding-github-a-journey-for-beginners-part-1

[6]	GitHub | CrunchBase
	https://www.crunchbase.com/organization/github

Select a site or more separated with ',' to pop (default = 0):  0
```

Of course this may not be happening to everyone but I don't want to think it happens only to me :alien: 

Sorry for the lack of description earlier...
Have a nice day!

**Comment by eavgerinos** [comment]
@alieus Thanks for the your extended analysis. :smile:

So, instead of adding a query parameter to the url every now and then, when Google decides to do so, why don't we just follow the redirects? Did you try this?

**Comment by eavgerinos** [comment]
Also we can use the `/ncr/` in order to avoid the redirections. It's a matter of taste after all I think...

**Comment by alieus** [comment]
`ncr` is good but I just couldn't find a way to search with it...
I tried `www.google.com/ncr/search?q=github` and `www.google.com/search/ncr?q=github` and it doesn't work...
But there must be a way!

Your are right that it's better to follow redirections than modifying the search url every time it breaks.
I 'll look at it when I have time.

But thinks can still break:
The regexps used to parse the search results depend on the format they are presented by Google; which may also change...
Also, Google simply blocks some user agents from search.
For example `wget -S http://www.google.com/search?q=la&gws_rd=cr` returns 403
while `wget -S --user-agent "Mozilla/5.0"  "http://www.google.gr/search?q=github"` works fine even without `&gws_rd=cr`..
So I just changed the url :relaxed: 

Maybe setting a good for value for the user agent can solve some problems..
I 'll also look at it when I have time..

**Comment by eavgerinos** [comment]
Setting user-agent and following redirects seems very elegant solution to me. :smile: Thanks for investigating the situation!

**Comment by eavgerinos** [comment]
Thanks for reporting. Fixed in #25 in a more clear way. Closing

**Pull request closed without merging**
